stages:
  - test

rust:deny:
  stage: test
  image: rust:1.91-alpine3.22
  before_script:
    - apk add cargo-deny
  script:
    - cargo deny check

rust:fmt:
  stage: test
  image: rust:1.91-alpine3.22
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

rust:clippy:
  stage: test
  image: rust:1.91-alpine3.22
  before_script:
    - apk add musl-dev
    - rustup component add clippy
  script:
    - cargo clippy --all-features -- -D warnings

rust:hack:
  stage: test
  image: rust:1.91-alpine3.22
  before_script:
    - apk add musl-dev cargo-hack
  script:
    - cargo hack check --feature-powerset --no-dev-deps

rust:test:
  stage: test
  image: rust:1.91-alpine3.22
  before_script:
    - apk add musl-dev
  script:
    - cargo test
    - cargo test --features axum
